#include"linkedlist.h"

int main(void)
{
	LINKED_LIST *L;
	L=CREATE_LINKED_LIST();
	LINKED_LIST_ADD_LAST(L,LINKED_LIST_NEWNODE(23));
	LINKED_LIST_ADD_LAST(L,LINKED_LIST_NEWNODE(23));
	LINKED_LIST_ADD_LAST(L,LINKED_LIST_NEWNODE(23));
	LINKED_LIST_ADD_LAST(L,LINKED_LIST_NEWNODE(23));
	LINKED_LIST_ADD_FIRST(L,LINKED_LIST_NEWNODE(328));
	LINKED_LIST_ADD_FIRST(L,LINKED_LIST_NEWNODE(328));
	LINKED_LIST_ADD_FIRST(L,LINKED_LIST_NEWNODE(328));
	LINKED_LIST_ADD_FIRST(L,LINKED_LIST_NEWNODE(328));
	PRINT_LINKED_LIST(L);
}
