#include"queue.h"

int main(void)
{
	QUEUE *Q;
	Q=CREATE_QUEUE();
	QUEUE_ENQUEUE(Q,NEW_QUEUE_NODE(32));
	QUEUE_ENQUEUE(Q,NEW_QUEUE_NODE(32));
	QUEUE_ENQUEUE(Q,NEW_QUEUE_NODE(32));
	QUEUE_ENQUEUE(Q,NEW_QUEUE_NODE(32));
	QUEUE_ENQUEUE(Q,NEW_QUEUE_NODE(32));
	PRINT_QUEUE(Q);
	QUEUE_DEQUEUE(Q);
	QUEUE_DEQUEUE(Q);
	QUEUE_DEQUEUE(Q);
	QUEUE_DEQUEUE(Q);
	QUEUE_DEQUEUE(Q);
	QUEUE_DEQUEUE(Q);
}
