#include"stack.h"

int main()
{
	STACK *S;
	S=CREATE_STACK();
	STACK_PUSH(S,NEW_STACK_NODE(32));
	STACK_PUSH(S,NEW_STACK_NODE(23));
	STACK_PUSH(S,NEW_STACK_NODE(99));
	STACK_PUSH(S,NEW_STACK_NODE(123));
	PRINT_STACK(S);
	STACK_POP(S);
	STACK_POP(S);
	STACK_POP(S);
	STACK_POP(S);
	STACK_POP(S);
}
